InventoryManagementSystem/Models/Inventory.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public class Inventory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InvontaryId { get; set; }

        [Required(ErrorMessage = "Please Enter Name")]
        [StringLength(300)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Plese Enter Units")]
        public double AvailableUnit { get; set; }

        [Required(ErrorMessage = "Please Enter Re-Order level ")]
        public double ReorderLevel { get; set; }

        [Required(ErrorMessage = "Please Enter Unit Price")]
        public double UnitPrice { get; set; }

        internal static IQueryable<Inventory> AsNoTracking()
        {
            throw new NotImplementedException();
        }
    }
}

InventoryManagementSystem/Controllers/InventoryController.cs
using InventoryManagementSystem.Context;
using InventoryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace InventoryManagementSystem.Controllers
{
    public class InventoryController : Controller
    {
       
        private readonly MVCContext _mvcContext;
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;

        public InventoryController(MVCContext context)
        {
            _mvcContext = context;
        }
        
        public IActionResult Index(int pg = 1)
        {
            List<Inventory> inventories = _mvcContext.Inventories.ToList();

            const int pageSize = 5;
            if(pg < 1)
                pg= 1;

            int restCount = inventories.Count;
            var pager = new Pager(restCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = inventories.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }

        public void connectonString()
        {
            con.ConnectionString = "Server=(localdb)\\mssqllocaldb;Database=InvontaryMnagement;Trusted_Connection=True;MultipleActiveResultSets=true";

        }

       
        [HttpGet]
        public IActionResult Create()
        {
            Inventory inv = new Inventory();
            return View(inv);
        }


        [HttpPost]
        public IActionResult Create(Inventory invontary)
        {
            var id = TempData["id"];
            int uid = (int)id;

            _mvcContext.Attach(invontary);
            _mvcContext.Entry(invontary).State = Microsoft.EntityFrameworkCore.EntityState.Added;
            _mvcContext.SaveChanges();

            connectonString();
            con.Open();
            com.Connection = con;
            com.CommandText = "select TOp 1 InvontaryId from Inventories ORDER BY InvontaryId DESC ";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                int iid = dr.GetInt32(0);
                TempData["i_id"] = iid;

            }
            con.Close();

            con.Open();
            int inv_id = (int)TempData["i_id"];

            com.CommandText = "insert into UserInventoryJunctions(InventoryId,UserId,Action) values('" + inv_id + "','" + uid +"','create')";
            dr = com.ExecuteReader();
            con.Close();
            return RedirectToAction("Index");

        }

        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            TempData["eid"] = id;
   
            Inventory invontary = _mvcContext.Inventories.Where(p => p.InvontaryId == id).FirstOrDefault();
            return View(invontary);

        }
        
         
        [HttpPost]
        public IActionResult Edit(Inventory invontary)
        {
            var id = TempData["id"];
            int uid = (int)id;
            var eid = TempData["eid"];
            int editid = (int)eid;

            _mvcContext.Attach(invontary);
            _mvcContext.Entry(invontary).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _mvcContext.SaveChanges();

            connectonString();
            con.Open();
            com.Connection = con;
            com.CommandText = "insert into UserInventoryJunctions(InventoryId,UserId,Action) values('" + editid + "','" + uid + "','Edit')";
            dr = com.ExecuteReader();
          
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            TempData["did"] = id;

            Inventory invontary = _mvcContext.Inventories.Where(p => p.InvontaryId == id).FirstOrDefault();
            return View(invontary);

        }

        [HttpPost]
        public IActionResult Delete(Inventory invontary)
        {

            var id = TempData["id"];
            int uid = (int)id;
            var did = TempData["did"];
            int deleteid = (int)did;

            _mvcContext.Attach(invontary);
            _mvcContext.Entry(invontary).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            _mvcContext.SaveChanges();

            connectonString();
            con.Open();
            com.Connection = con;
            com.CommandText = "insert into UserInventoryJunctions(InventoryId,UserId,Action) values('" + deleteid + "','" + uid + "','Delete')";
            dr = com.ExecuteReader();
            return RedirectToAction("Index");

        }


        public IActionResult Detail(int id)
        {
            Inventory invontary = _mvcContext.Inventories.Where(p => p.InvontaryId == id).FirstOrDefault();
            return View(invontary);

        }


    }
}

InventoryManagementSystem/Views/Inventory/Create.cshtml
@model InventoryManagementSystem.Models.Inventory

@{
    ViewData["Title"] = "Create";
}

<body style="background-color:#E6E6FA;">
<nav class="navbar navbar-light bg-dark">
  <span class="navbar-brand mb-0 h1"  style="margin-left:40px;"> <a asp-action="Index" asp-controller="Inventory" style="color:white; text-decoration:none;">Inventory</a></span>
</nav>
 <br/>

<h1 align="center">Create New Inventory Item</h1

<hr />
<div class="row" style="margin-left:400px;" >
    <div class="col-md-7" >
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <br/>  
            <div class="form-group">
                <label asp-for="Name" class="control-label" style ="font-weight:bold;"> Name</label>  
                <input asp-for="Name" class="form-control"   placeholder="Enter Name"/>
               <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="AvailableUnit" class="control-label" style ="font-weight:bold;">Available Unit</label>
                <input asp-for="AvailableUnit" class="form-control" placeholder="Enter Units />
                 <span asp-validation-for="AvailableUnit" class="text-danger"></span>
            </div>
             <br/>
            <div class="form-group">
                <label asp-for="ReorderLevel" class="control-label" style ="font-weight:bold;"> Re-Order Level</label>
                <input asp-for="ReorderLevel" class="form-control" placeholder="Enter Re-order level"/>
                <span asp-validation-for="ReorderLevel" class="text-danger"></span>
            </div>
             <br/>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label" style ="font-weight:bold;">Unit Price</label>
                <input asp-for="UnitPrice" class="form-control" placeholder="Enter Unit Price"/>
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
              <br/> <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <button  class="btn btn-success" style="margin-left:350px;">
                <a asp-action="Index" style="color:white; text-decoration:none;">Back to List</a>
                </button>
            </div>
              <br/>
        </form>
    </div>
</div>
<br/><br/>
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>
</body>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagementSystem/Views/Inventory/Delete.cshtml
@model InventoryManagementSystem.Models.Inventory

@{
    ViewData["Title"] = "Delete";
}

<body style="background-color:#C0C0C0;">
    <nav class="navbar navbar-light bg-dark">
    <span class="navbar-brand mb-0 h1"  style="margin-left:40px;"> <a asp-action="Index"asp-controller="Inventory" style="color:white; text-decoration:none;">Inventory</a></span>
    </nav>
    <br/>
    <h1 align="center"> Are You Want To Delete This?</h1>
    <hr/>
    <div class="card" style="width:700px;height:300px; margin-left:350px;" >
      <div class="card-body">
      <div>
    <br/><br/>

    <dl class="row">
        <dt class = "col-sm-2">
            Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class = "col-sm-2">
         Units
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvailableUnit)
        </dd>
        
        <dt class = "col-sm-2">
             Level
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReorderLevel)
        </dd>
          
        <dt class = "col-sm-2">
            Price
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        </dl>
        <br>
    <form asp-action="Delete">
        <div  class="form-group">

            <input type="hidden" asp-for="InvontaryId" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <button class="btn btn-success" style="margin-left:350px"> 
                <a asp-action="Index" style="color:white; text-decoration:none;">Back to List</a>
            </button>

        </div>
    </form>
     </div>
        </div>
        </div>

        <br/><br/><br/><br/><br/><br/><br/>

  <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>

       
 </body>
    

InventoryManagementSystem/Views/Inventory/Detail.cshtml
@model InventoryManagementSystem.Models.Inventory

@{
    ViewData["Title"] = "Detail";
}

<body style="background-color:#C0C0C0;">
    <nav class="navbar navbar-light bg-dark">
      <span class="navbar-brand mb-0 h1"  style="margin-left:40px;"> <a asp-action="Index" asp-controller="Inventory" style="color:white; text-decoration:none;">Inventory</a></span>
    </nav>
    <br/>
    <h1 align="center"> Inventory Item Details</h1>
   <br/><br/>

    <div class="card" style="width:700px; margin-left:400px;" >
      <div class="card-body">
      <div>
    
     <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class = "col-sm-2">
         Units
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvailableUnit)
        </dd>
        
        <dt class = "col-sm-2">
             Level
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReorderLevel)
        </dd>
          
        <dt class = "col-sm-2">
            Price
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
         
    </dl>
</div>


<div class="form-group">
   <button class="btn btn-primary"> <a asp-action="Edit" asp-route-id="@Model?.InvontaryId" style="color:white; text-decoration:none;">Edit</a> </button>
   <button class="btn btn-success" style="margin-left:350px"> <a asp-action="Index" style="color:white; text-decoration:none;">Back to List</a></button
</div>

    </div>
  </div>
</div>
<br/><br/><br/><br/><br/><br/><br/>
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>
</body>

InventoryManagementSystem/Views/Inventory/Edit.cshtml
@model InventoryManagementSystem.Models.Inventory

@{
    ViewData["Title"] = "Edit";
}

<body style="background-color:#C0C0C0;">
    <nav class="navbar navbar-light bg-dark">
    <span class="navbar-brand mb-0 h1"  style="margin-left:40px;"> <a asp-action="Index" asp-controller="Inventory" style="color:white; text-decoration:none;">Inventory</a></span>
    </nav>
    <br/>
    <h1 align="center">Edit Inventory Item</h1>
    <hr/>

    
  <div class="row" style="margin-left:400px;" >
    <div class="col-md-7">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InvontaryId" />
             <br/>
            <div class="form-group">
                <label asp-for="Name" class="control-label" style ="font-weight:bold;">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
             <br/>
            <div class="form-group">
                <label asp-for="AvailableUnit" class="control-label" style ="font-weight:bold;">Available Unit</label>
                <input asp-for="AvailableUnit" class="form-control"  />
                <span asp-validation-for="AvailableUnit" class="text-danger"></span>
            </div>
             <br/>
            <div class="form-group">
                <label asp-for="ReorderLevel" class="control-label" style ="font-weight:bold;">Re-Order Level</label>
                <input asp-for="ReorderLevel" class="form-control" />
                <span asp-validation-for="ReorderLevel" class="text-danger"></span>
            </div>
             <br/>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label" style ="font-weight:bold;">Unit Price</label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
             <br/> <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                 <button  class="btn btn-success" style="margin-left:350px;">
                <a asp-action="Index" style="color:white; text-decoration:none;">Back to List</a>
                </button>
            </div>
            <br/>

        </form>
    </div>
</div>

<br/><br/>

<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>
</body>
   





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagementSystem/Views/Inventory/Index.cshtml
@model IEnumerable<InventoryManagementSystem.Models.Inventory>

@{
    ViewData["Title"] = "Index";

    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<body style="background-color:#E6E6FA;">
<nav class="navbar navbar-light bg-dark">
  <span class="navbar-brand mb-0 h1"  style="margin-left:40px;"> <a asp-action="Index" style="color:white; text-decoration:none;">Inventory</a></span>
  <span class="navbar-brand mb-0 h1"  style="margin-left:40px; float:right;"> <a asp-action="Index" asp-controller="Home" style="color:white; text-decoration:none;">Logout</a></span>
</nav>
 <br/>

<h1 align="center">Inventory Items</h1>
<hr />

<p>
    <button class="btn btn-primary" style="margin-left:100px;  float:left;">
         <a asp-action="Create" style="color:white; text-decoration:none;">Create New</a>
    </button>
   
</p>
<partial name="_Pager" model="@pager" style="margin-right:100px; float:right" />
<table  class="table table-striped" style="margin-left:100px; margin-right:100px; width:1200px;" >
    <thead>
        <tr>
            <th>  Id </th>
            <th> Name </th>
            <th> Availabale Units </th>
            <th> Re- Order Level </th>
            <th> Unit Price  </th>
            <th>Actions</th>
            <th>Actions</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody >
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.InvontaryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableUnit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReorderLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                <button class="btn btn-success"><a asp-action="Edit" asp-route-id="@item.InvontaryId" style="color:white; text-decoration:none;">Edit</a></button>
            </td>
             <td>
                <button class="btn btn-warning">
                    <a asp-action="Detail" asp-route-id="@item.InvontaryId" style="color:white; text-decoration:none;">Details</a>
                 </button>
            <td>
                <button class="btn btn-danger"><a asp-action="Delete" asp-route-id="@item.InvontaryId" style="color:white; text-decoration:none;">Delete</a></button>
            </td>
                
        </tr>
}
    </tbody>
</table>
</body>
<partial name="_Pager" model="@pager" />